#!/usr/bin/python3
#SPDX-FileCopyrightText: 2025 TakeSomen99
#SPDX-License-Identifier: BSD-3-Clause

import sys
import re
import string
import numpy as np
import unicodedata as uni


class InputError(Exception):
    pass


class UnexpectedError(Exception):
    pass


def input_error_check(i):
    if i == "":
        raise InputError("input is empty")
    if " " in i:
        raise InputError("input has a space")
    for c in i:
        if uni.east_asian_width(c) in 'FHW':
            raise InputError("input has a double width character")
    
    return i


def analys_password_for_length(password):
    safe_score = 0

    if(len(password) < 6):
        safe_score = 1
    elif(len(password) < 8):
        safe_score = 2
    elif(len(password) < 10):
        safe_score = 3
    elif(len(password) < 12):
        safe_score = 4
    elif(len(password) < 14):
        safe_score = 5
    else:
        safe_score = 6
    final_score = safe_score / 6
    return final_score


def analys_password_for_chartype(password):
    safe_score = 0
    if(re.search(r'[a-z]',password)):
        safe_score += 1
    if(re.search(r'[A-Z]',password)):
        safe_score += 1
    if(re.search(r'[0-9]',password)):
        safe_score += 1
    if(re.search(r'[^a-zA-Z0-9]',password)):
        safe_score += 1
    final_score = safe_score / 4
    return final_score


def analys_password_for_diversity(password):
    _lower = set(string.ascii_lowercase)
    _upper = set(string.ascii_uppercase)
    _digit = set(string.digits)

    _symbol32 = set(r"""`~!@#$%^&*()_+-={}[]|\:;"'<>,.?/""")
    _symbol22 = set("!$%&'()*+,/;<=>?[]^{}~")
    _symbol12 = set("$-./:@[]!#&?")

    classified = {
            "lower": set(),
            "upper": set(),
            "digit": set(),
            "symbol": set()
            }

    for c in password:
        if c in _lower:
            classified["lower"].add(c)
        elif c in _upper:
            classified["upper"].add(c)
        elif c in _digit:
            classified["digit"].add(c)
        elif c in _symbol32:
            classified["symbol"].add(c)

    symbolset = 1
    if classified["symbol"] <= _symbol12:
        symbolset = len(_symbol12)
    elif classified["symbol"] <= _symbol22:
        symbolset = len(_symbol22)
    elif classified["symbol"] <= _symbol32:
        symbolset = len(_symbol32)

    coverage = (
            len(classified["lower"])/len(_lower) +
            len(classified["upper"])/len(_upper) +
            len(classified["digit"])/len(_digit) +
            len(classified["symbol"])/symbolset
            ) / 4
    return coverage


def analys_password_for_distribution(password):
    length = len(password)
    data = {
            "lower": [],
            "upper": [],
            "digit": [],
            "symbol": []
    }

    for i, c in enumerate(password):
        if(c.islower()):
            data["lower"].append(i)
        elif(c.isupper()):
            data["upper"].append(i)
        elif(c.isdigit()):
            data["digit"].append(i)
        else:
            data["symbol"].append(i)
    normalized_values = []
    for datum in data.values():
        if len(datum) > 1:
            value = np.var(datum) / (length ** 2)
            normalized_values.append(value)
        else:
            normalized_values.append(0.0)
    if normalized_values:
        return np.mean(normalized_values) / 0.25
    else:
        return 0.0


def main():
    password = input()

    input_error_check(password)

    len_score = analys_password_for_length(password)
    cha_score = analys_password_for_chartype(password)
    div_score = analys_password_for_diversity(password)
    dis_score = analys_password_for_distribution(password)

    final_score = (len_score + cha_score + div_score + dis_score) / 4
    final_score_rounded = round(final_score,2)

    if final_score_rounded < 0 or final_score_rounded > 1:
        raise UnexpectedError("result value dose not fall between 0 and 1")

    print(final_score_rounded)


if __name__ == "__main__":
    try:
        main()
    except InputError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    except UnexpectedError as e:
        print(f"UnexpectedError: {e}", file=sys.stderr)
        sys.exit(2)
