#!/usr/bin/python3
#SPDX-FileCopyrightText: 2025 TakeSomen99

import sys
ans = 0 #もともと0.0だったものを0に変更
for line in sys.stdin:
    try:
        ans += int(line)
    except:
        ans += float(line)
print(ans)
